// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAogILb-U0SACFTE_5DejLzdlC6YvFrN8A',
    appId: '1:939895024527:web:1b4b78f608caa595a379fa',
    messagingSenderId: '939895024527',
    projectId: 'campusconnect-41d4a',
    authDomain: 'campusconnect-41d4a.firebaseapp.com',
    storageBucket: 'campusconnect-41d4a.firebasestorage.app',
    measurementId: 'G-T38BD79JPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4UPTaoZEL-3LZOWEnUd-8_Z8Yx_BfThQ',
    appId: '1:939895024527:android:16ae295a21123d03a379fa',
    messagingSenderId: '939895024527',
    projectId: 'campusconnect-41d4a',
    storageBucket: 'campusconnect-41d4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUumTtjj-6sLnixTq9fgduuf28LaHOVI',
    appId: '1:939895024527:ios:e9ba8ea18a463efea379fa',
    messagingSenderId: '939895024527',
    projectId: 'campusconnect-41d4a',
    storageBucket: 'campusconnect-41d4a.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUumTtjj-6sLnixTq9fgduuf28LaHOVI',
    appId: '1:939895024527:ios:e9ba8ea18a463efea379fa',
    messagingSenderId: '939895024527',
    projectId: 'campusconnect-41d4a',
    storageBucket: 'campusconnect-41d4a.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAogILb-U0SACFTE_5DejLzdlC6YvFrN8A',
    appId: '1:939895024527:web:f106f5f6b8f2e28aa379fa',
    messagingSenderId: '939895024527',
    projectId: 'campusconnect-41d4a',
    authDomain: 'campusconnect-41d4a.firebaseapp.com',
    storageBucket: 'campusconnect-41d4a.firebasestorage.app',
    measurementId: 'G-792GXHJ72J',
  );
}
